### ISSUE TITLE
Error "unknown flag at position 11" in minimal example

### ISSUE THREAD

**Issue by mtewes** [cqql/pelican-katex#1]
Hi cqql!
we (@mtewes and @fkleinebreil) re trying to get a minimal pelican-katex example to work. We're using python 3.5.6, pelican 4.2.0, nodejs 0.1.1, pelican-katex 1.2.3.

As soon as we add ```PLUGINS = ["pelican_katex"]``` to the config, building the site fails with the error ```CRITICAL: error: unknown flag at position 11```.

The actual page source seems not relevant for this error, but it is
A page source is :

```
Test
####

Test 

.. math::
	\pi = 3

```

Any ideas?

**Comment by cqql** [comment]
Hey,
great to hear that you are trying this out! I have tried your page on my computer and everything works flawlessly. One thing that immediately stands out to me is that your nodejs version is *very* old. Version 0.1.1 is not even available on the [previous releases page](https://nodejs.org/en/download/releases/) anymore that reaches back over 8 years. Could you try again with a version that is somewhat recent? If it still does not work, please try running pelican with `-D` for the complete debug output.

**Comment by mtewes** [comment]
Hi Marten,

thanks for noticing the old nodejs! I guess I got it via pip without paying attention.

I've created a new environment from scratch, this time installing nodejs first and via conda, and only installing pelican and pelican_katex afterwards via pip.

```
conda create --name pelican3.7 python=3.7
conda activate pelican3.7
conda install nodejs
pip install pelican
pip install pelican-katex

make clean
make devserver
```
This gives python 3.7.5, nodejs 10.13.0, pelican 4.2.0, and pelican-katex 1.2.3.
Pelican now runs fine, without errors or warnings, but equations are shown "twice" in the output. The source (I changed it to test, but the content does not seem to matter)...
```
.. math::
  x^n + y^n = z^n
```

... gives (in Safari and Firefox) ... 
![Screenshot 2019-11-18 at 11 26 46](https://user-images.githubusercontent.com/1928653/69045773-d696ca80-09f7-11ea-8526-bb6120fd5ef4.png)

... and the relevant line of the generated  html is
```
<span class="katex-display"><span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msup><mi>x</mi><mi>n</mi></msup><mo>+</mo><msup><mi>y</mi><mi>n</mi></msup><mo>=</mo><msup><mi>z</mi><mi>n</mi></msup></mrow><annotation encoding="application/x-tex">x^n + y^n = z^n</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.7977219999999999em;vertical-align:-0.08333em;"></span><span class="mord"><span class="mord mathdefault">x</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.7143919999999999em;"><span style="top:-3.113em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathdefault mtight">n</span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:0.2222222222222222em;"></span><span class="mbin">+</span><span class="mspace" style="margin-right:0.2222222222222222em;"></span></span><span class="base"><span class="strut" style="height:0.9088319999999999em;vertical-align:-0.19444em;"></span><span class="mord"><span class="mord mathdefault" style="margin-right:0.03588em;">y</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.7143919999999999em;"><span style="top:-3.113em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathdefault mtight">n</span></span></span></span></span></span></span></span><span class="mspace" style="margin-right:0.2777777777777778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2777777777777778em;"></span></span><span class="base"><span class="strut" style="height:0.7143919999999999em;vertical-align:0em;"></span><span class="mord"><span class="mord mathdefault" style="margin-right:0.04398em;">z</span><span class="msupsub"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.7143919999999999em;"><span style="top:-3.113em;margin-right:0.05em;"><span class="pstrut" style="height:2.7em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mathdefault mtight">n</span></span></span></span></span></span></span></span></span></span></span></span>
```

Any ideas of what is going wrong this time? Sorry for bugging you again...

**Comment by cqql** [comment]
The output has the rendered equation as well as the source as an
annotation. The reason that both are shown could be that the katex
stylesheet is missing. Did you include it? pelican-katex pre-renders the
equations but you still need to serve the stylesheet with your website to
display them nicely. If that is the case, I should add that to the readme
to make it clearer.

**Comment by mtewes** [comment]
Ah indeed, I didn't include any stylesheet...
Adding the css as shown on https://katex.org/docs/browser.html makes it work, and looks great.
BTW I also found https://gitlab.com/thousandyardstare/pelican-latex-prerender which also requires the inclusion of katex CSS.
Thanks for your answers!

**Comment by cqql** [comment]
Great! I have added a precautionary sentence to the readme.
